### ISSUE TITLE
Parsing error for using final block

### ISSUE THREAD

**Issue by austinabell** [near/near-cli-rs#104]
Not sure if something to do with infra or if I'm using an outdated version, so will close if one of those cases, but opening because js cli works for this.

```bash
Your console command:
./near-cli execute view-method network testnet contract hello_sat.testnet call hello {} at-final-block
Error:
   0: serde json: Error("EOF while parsing a value", line: 1, column: 0)

Location:
   src/commands/execute_command/view_method/block_id/mod.rs:101
```

**Comment by miraclx** [comment]
```jsonc
$ xh https://rpc.testnet.near.org jsonrpc=2.0 id=dontcare method=query params:='{ "request_type": "call_function", "account_id": "hello_sat.testnet", "method_name": "hello", "args_base64": "e30=", "finality": "final" }'
{
    "jsonrpc": "2.0",
    "result": {
        "block_hash": "GYzwUXWzA5pW9TxP4SLtDpq8VCf5CjshscmVLEqSJFCr",
        "block_height": 88501717,
        "logs": [
            "Hello World"
        ],
        "result": [] // <- empty response
    },
    "id": "dontcare"
}
```

Should be an easy fix. We just need to extend the response handling to account for empty function call results.

https://github.com/near/near-cli-rs/blob/6373bb99d46a629993bc287dce193f04ec8060ea/src/commands/execute_command/view_method/block_id/mod.rs#L96-L98

**Comment by miraclx** [comment]
Even `near-cli-js` returns `false` because `near-api-js` short-circuits during a conditional check.

```console
$ NEAR_ENV=testnet near view hello_sat.testnet hello '{}'
View call: hello_sat.testnet.hello({})
Log [hello_sat.testnet]: Hello World
false
```

Reference: https://github.com/near/near-api-js/blob/6f83d39f47624b4223746c0d27d10f78471575f7/src/account.ts#L537

**Comment by austinabell** [comment]
Perhaps a view should fail if there is no return value, although not certain this should be the case, but at least a less cryptic error should be emitted here (or in both) as it's not clear it's expecting a serialized result value.

**Comment by miraclx** [comment]
`null` seems to be most convenient here, as it signifies the absence of a value. Lmk what you think on https://github.com/near/near-cli-rs/pull/105.
