### ISSUE TITLE
Show the logs for view function calls

### ISSUE THREAD

**Issue by miraclx** [near/near-cli-rs#106]
On `near-cli-js`, when you make a view function call, it conveniently prints the logs associated with that function call before finally printing the result. Would be useful to be able to do the same, even if it's behind an CLI argument like `--logs`.

Example:

<pre>$ NEAR_ENV=testnet near view hello_sat.testnet hello '{}'
 View call: hello_sat.testnet.hello({})
 Log <span class="error">[hello_sat.testnet]</span>: Hello World
 false</pre>

Proposed: (of course, all the decorators should print to stderr, while the result itself prints to stdout)

<pre>$ near-cli execute view-method network testnet \
 contract nosedive.testnet call status 

 {"account_id":"miraclx.near"} 

 at-final-block

--------------

Logs:
 Hello World

--------------

Result:
 {
 "rating": 3.4847097,
 "given": 4,
 "received": 8
 }

--------------

Your console command:
 target/debug/near-cli execute view-method network testnet contract hello_sat.testnet call hello {} at-final-block</pre>

**Comment by ermolushka** [comment]
Hey, if it's still required I may work on it.

**Comment by frol** [comment]
@ermolushka go for it! 🙏
