### ISSUE TITLE
Cancelling interactive session breaks the shell cursor

### ISSUE THREAD

**Issue by mfornet** [near/near-cli-rs#130]
When I'm writing an interactive command and decide to cancel it (using Ctrl+C), I get back to the terminal, but the cursor in the shell doesn't appear anymore. I'm using fish (as my shell).

**Comment by frol** [comment]
Thanks for reporting it. It is indeed annoying; I hope it will be fixed with https://github.com/near/near-cli-rs/issues/97#issuecomment-1280503299

**Comment by frol** [comment]
Resolved with #144
