### ISSUE TITLE
Description error when presenting FunctionCall key

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-cli-rs#133]
when a FunctionCall key's method list is empty, it should show `is granted to do any function calls` rather than `is granted to only do [] function calls`

**Comment by frol** [comment]
@hanakannzashi That is right! Would you consider submitting a PR fixing it?

Here is the code that needs to handle the empty list and produce the correct message:

https://github.com/near/near-cli-rs/blob/a8679a3603015f1d651f874fdf0feff0d7514131/src/common.rs#L1294-L1297
