### ISSUE TITLE
Implement `near login`-like flow

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#14]
The official <span class="error">[`near-cli`]</span>([https://github.com/near/near-cli](https://github.com/near/near-cli)) supports `near login` command, which essentially adds a new key to an account through NEAR Wallet. See "Add Access Key (and "login")" in [https://github.com/near/NEPs/pull/31#issuecomment-815342791](https://github.com/near/NEPs/pull/31#issuecomment-815342791)

**Comment by frol** [comment]
Update: here is the draft: https://github.com/frol/cli_dialoguer_strum_3/commit/abe18c2f129d3db88e4014cd4ee00ca778ef6f50

**Comment by StarGachinum** [comment]
I will do it.

**Comment by frol** [comment]
It is implemented already, you can use the following command:

```shell
near account import-account using-web-wallet
```
