### ISSUE TITLE
Improve UX of CLI: the commands are too long

### ISSUE THREAD

**Issue by robert-zaremba** [near/near-cli-rs#145]
consider near-cli:
```
near-cli contract call-function as-transaction [CONTRACT_ACCOUNT_ID] [FUNCTION_NAME] [FUNCTION_ARGS_TYPE] [FUNCTION_ARGS] [COMMAND]
```
versus
```
near call <contractName> <methodName> [args]
```

The former is utterly long.

**Comment by frol** [comment]
@robert-zaremba Thanks for opening this conversation! I believe it is a feature, not a bug. The latter is utterly ambiguous and misleading and not reproducible.

* Is it going to call a contract on testnet or mainnet?
  * **Answer:** it depends on the env variables
* Is it going to be a "view-function" call or a "change-function" call?
  * **Answer:** it is a transaction "change-function" call. Follow-up question: guess how the non-transaction / "read-only" / "view-function" call command is named and how to even discover it
* How much Gas is attached?
  * **Answer:** there is some default that is only reasonable for simple contract calls
* Who is going to be the sender of this call?
  * **Answer:** there should be `--masterAccount` arg specified, and if you add it, the command is not slim anymore

This CLI has interactive mode and I don't expect users to type out all the commands by memory, instead, I envision them to be guided by the interactive prompts and receive a final command at the end if they want to replay the same command or tweak the command the next time. There was a similar discussion before: https://github.com/near/near-cli-rs/pull/75#discussion_r875039241

**Comment by robert-zaremba** [comment]
power users won't use interactive mode

**Comment by willemneal** [comment]
I think that this works well if it's all prompts from the start, but I agree most CLI users would prefer to write out the command.

@robert-zaremba You can also create a plugin for the cli, like cargo, e.g. `near-cli-your-plugin` which would cover your use case. Would just need to alias `near-cli` to `near-cli your-plugin`.

**Comment by miraclx** [comment]
I think a potential resolution for this is to have shell completions, so double-<kbd>tab</kbd> and you can see possible options for the next entry in the command line.

**Comment by frol** [comment]
> power users won't use interactive mode

The power users I know enjoy the fact that the very first time they use the CLI they were walked through the process and at the end they have a copy-pastable command that they just use via scripts or replay/edit it and they re-use later from the shell history without thinking which env variables they have set in the current session.
