### ISSUE TITLE
NEAR Import Account

### ISSUE THREAD

**Issue by doriancrutcher** [near/near-cli-rs#158]
If possible we should implement the wallet selector as the means of importing a full access key using the web wallet option. That way it opens up this tool to more users :) 

Right now it only points to wallet.testnet.near.org

**Comment by frol** [comment]
@doriancrutcher Thanks for submitting an idea! I wonder, though if all the wallets have this support (MyNearWallet and the original Web wallet do, but I doubt that others that are not based on the same code-base, support adding full-access keys via URL); ideally, there should be a Wallet Standard that defines the URL and parameters as currently we kind of rely on a non-documented feature.

**Comment by frol** [comment]
Resolved in #218
