### ISSUE TITLE
NEAR Login redirects to wallet.near.org

### ISSUE THREAD

**Issue by doriancrutcher** [near/near-cli-rs#161]
Hey hey, 

I noticed that the login feature redirects to wallet.near.org. 

I was wondering if We should change this to the wallet selector instead. 

Or mynearwallet depending on the direction we are headed

**Comment by frol** [comment]
@doriancrutcher Is it a duplicate of #158? If not, please, help me to understand the difference.

**Comment by frol** [comment]
If you want a temporary solution, you can edit the wallet URL in [near-cli-rs config](https://github.com/near/near-cli-rs/blob/master/docs/README.en.md#config), so it points to mynearwallet instead.

**Comment by frol** [comment]
Resolved in #218
