### ISSUE TITLE
call function with file args shows wrong log

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-cli-rs#186]
When call a function with `file-args` such as wasm code, it will show that args is `null` in console. (only log error, function call itself is fine)

<img width="419" alt="截屏2023-04-22 13 12 23" src="https://user-images.githubusercontent.com/95295094/233763983-07867551-8781-4e58-8d13-9df6d802b7b2.png">

**Comment by frol** [comment]
Oh, I guess it is a display bug. I would display “<non-JSON data (X kb)>”.

@hanakannzashi Would you be open to submit a PR with the fix? I believe we need to refactor this line: https://github.com/near/near-cli-rs/blob/b34e0ce744fc43932ef3bf359c4997f2da92add9/src/common.rs#L743, currently .unwrap_or_default() leads to `null`

**Comment by Chubik** [comment]
I did https://github.com/near/near-cli-rs/pull/187
