### ISSUE TITLE
Implement system keychain support for Windows and Linux

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#195]
Currently, near-cli-rs only supports macOS keychain to store access keys (it stores JSON data with private key as a password entry in the keychain and reads it in memory when user wants to sign a transaction).

There is a nice crate that has Windows, Linux, macOS, and iOS support: https://docs.rs/keyring/. I suggest we try using it and rename the “macos-keychain” commands into “keychain” and the current “keychain” into “legacy-keychain”. For backwards compatibility, the new “keychain” command should check the legacy keychain folder when signing transactions if there is no accesss key in the system keychain before returning an error.

---

_If anyone wants to work on this feature, feel free to ask any questions in the comments and I’m happy to give you pointers about where to start_

**Comment by gautamprikshit1** [comment]
Can you provide with some extra pointers to get started on this issue. Thanks in advance

**Comment by frol** [comment]
Here is the most relevant starting point: https://github.com/near/near-cli-rs/blob/251e45fbe6fc8ea730df4a942dc86274a27c9fe5/src/transaction_signature_options/sign_with_macos_keychain/mod.rs

`keychain` is instantiated there:

https://github.com/near/near-cli-rs/blob/251e45fbe6fc8ea730df4a942dc86274a27c9fe5/src/transaction_signature_options/sign_with_macos_keychain/mod.rs#L49C13-L49C21

and then used later.

This module is feature-gated and only available on macOS (for obvious reasons). The `keyring` crate above should be able to help us to implement similar logic, but for all the major platforms at once.

**Comment by shariffdev** [comment]
@frol I put up a PR for this here https://github.com/near/near-cli-rs/pull/232
