### ISSUE TITLE
Order networks selection based on the selected account id

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#222]
Currently, when prompted to select network `near` CLI uses the order specified in the config.toml, it would be useful if we could bubble up network configs relevant to the specified account id (e.g. when `frol.testnet` is specified, we would move all the "testnet" connections up before mainnet ones).

<img width="1144" alt="image" src="https://github.com/near/near-cli-rs/assets/304265/eb690be2-0a7c-46e1-8d90-322f56e39e12">

(^ I wish that 3 last items would be at the beginning of the list)

Note that implicit account ids are not guessable, while named accounts end with `.near` suffix on mainnet, and with `.testnet` on testnet. NetworkConnection has `network_name` that can be used to identify the relevant network connection.

**Comment by thaodt** [comment]
I'm working on this one.

**Comment by frol** [comment]
Resolved in #225
