### ISSUE TITLE
New command to view contract storage state

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#223]
Sometimes, it is useful to inspect raw contract storage state even though near-sdk-rs uses borsh to serialize keys and values. 

near CLI JS has `near view-state <account-id> [OPTIONAL_STORAGE_KEY_PREFIX]` command, and I initially planned (#128) to implement it in a separate "dev" extension, but now I feel this raw viewing mode belongs here.

```
near contract view-storage <contract-account-id> all network-config testnet now
near contract view-storage <contract-account-id> keys-start-with-string "S" network-config testnet now
near contract view-storage <contract-account-id> keys-start-with-bytes-as-base64 "Uw==" network-config testnet now
```

**Comment by thaodt** [comment]
I also take this, please leave it to me. Thanks.
