### ISSUE TITLE
Need help: enter account-id and saving path

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-cli-rs#228]
When I try to import an account by cli, I use `near account import-account using-seed-phrase "${SEED_PHRASE}" --seed-phrase-hd-path 'm/44'\''/397'\''/0'\''' network-config testnet`, but I still need to interact with cli to input account id and select the keychain. How can I directly complete all options with one command?

**Comment by hanakannzashi** [comment]
How to build near-cli-rs locally?

**Comment by frol** [comment]
> How to build near-cli-rs locally?

@hanakannzashi `cargo build`

**Comment by frol** [comment]
> How can I directly complete all options with one command?

@hanakannzashi Please, share your use case. I always viewed account importing to be an interactive task. If you want to sign a transaction in an automated way, you can use `sign-with-seed-phrase` and specify it there directly instead of importing the key first.
