### ISSUE TITLE
CLI must return a non-zero exit code when function call (as-transaction) fails

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#233]
When I run the following command, I get the error message in the text, but exit-code is still zero:

```
near contract call-function as-transaction YOUR_ACCOUNT.testnet asd json-args {} prepaid-gas '100.000 TeraGas' attached-deposit '0 NEAR' sign-as YOUR_ACCOUNT.testnet network-config testnet
```

See the error:

<img width="1491" alt="image" src="https://github.com/near/near-cli-rs/assets/304265/3d60c659-3c55-4800-a6a2-4323fd14ad89">

Check exit code after the command:

```
echo $?
```

It prints zero, but should print some non-zero value, like `as-read-only` does:

<img width="987" alt="image" src="https://github.com/near/near-cli-rs/assets/304265/6a0164da-3726-4ecf-8abd-978ded0d6426">

**Comment by FroVolod** [comment]
I fixed this issue. The screenshots show _near-cli_ before and after the fix.
![Screenshot 2023-09-04 at 14 41 14](https://github.com/near/near-cli-rs/assets/36816899/cb53d061-f04d-466e-80e8-547a58ffac84)
![Screenshot 2023-09-04 at 15 42 34](https://github.com/near/near-cli-rs/assets/36816899/6cbd1c35-bc24-456a-8444-c2c548d0c0aa)
