### ISSUE TITLE
Implement dev-deploy

### ISSUE THREAD

**Issue by gagdiez** [near/near-cli-rs#255]
People uses a lot this method, and is one of the main commands we will need for removing the current `near-cli-js` from all our tutorials.

Either we implement this, or:
1. Come up with a new flow explaining people how to create `dev` accounts
2. Completely ditch `dev` account (an idea really to consider, since people get confused about the `dev` accounts a lot)

While writing this, I am feeling maybe we should just do (2) instead of implementing the `dev-deploy`, but would like to hear opinions from the devs of this tool.

**Comment by frol** [comment]
@gagdiez I believe that `dev-deploy` is responsible for the developers drop off as with this magic you don't know how to have a normal account id, how to deploy to mainnet, etc.

`cargo-near` has two methods instead:

```
cargo near create-dev-account
```

and then

```
cargo near deploy
```

Would you like to give it a try and see if that helps?

P.S. I also want to link #235 here.

**Comment by gagdiez** [comment]
I agree that `dev-deploy` should not be ported, and maybe even removed from the `near-cli-js`. Closing this issue now.
