### ISSUE TITLE
Weird available balance report

### ISSUE THREAD

**Issue by miraclx** [near/near-cli-rs#257]
An account with insufficient balance for storage + ~tx costs seems to have its "available balance" wrapped around. Makes me think I have more money than I (or anyone) does 😄.

```console
$ near tokens alt.miraclx.near view-near-balance network-config mainnet now

alt.miraclx.near account has 340282366920938.460863748557431768211456 NEAR available for transfer (the total balance is 0.00022037395 NEAR, but 0.00182 NEAR is locked for storage and the transfer transaction fee is ~0.001 NEAR)

Here is your console command if you need to script it or re-run:
near tokens alt.miraclx.near view-near-balance network-config mainnet now
```

Here's the relevant bit of code: https://github.com/near/near-cli-rs/blob/dd82e7b81bc7bce439347d6a73b119219edef05b/src/common.rs#L147-L149

Looks like that pulls into logic within https://github.com/near/near-token-rs

**Comment by frolvanya** [comment]
I think this issue was resolved within the latest update. Please, run `near extensions self-update`

<img width="1254" alt="image" src="https://github.com/near/near-cli-rs/assets/59515280/bd46e55f-b54a-4049-829b-f70c35e36868">
