### ISSUE TITLE
Enhanced key management

### ISSUE THREAD

**Issue by alexauroradev** [near/near-cli-rs#267]
At the moment the function
`$ near account list-keys <account> network-config mainnet now`
displays the keys of the account in an order, presumably, from the newest to the oldest. It would be good to be able to specify listing of full access keys only or highlight somehow these keys. It is important for keeping the clean setup of all keys within an account. Similar issue is with function call keys with infinite allowance.

Besides that it would be nice to be able to manage the keys straight away from the table that is an output of the call. Ideally, a user can navigate the keys using arrows and able to delete them with one key press. The flow should allow for multiple key deletions.

At the moment the cleanup of the keys associated with the account requires periodic display of the key list and manual copying of the keys and deleting them one by one.

**Comment by frol** [comment]
Thanks for the suggestion!

> At the moment the cleanup of the keys associated with the account requires periodic display of the key list and manual copying of the keys and deleting them one by one.

@alexauroradev Would it help if `delete-keys` had a multi-select of all the keys listed there with their type in parenthesis?
