### ISSUE TITLE
CLI Issues and Deprecated Commands in NEAR FastAuth-SDK Documentation

### ISSUE THREAD

**Issue by ShunsukeKano** [near/near-cli-rs#276]
I'm currently following the documentation provided at https://docs.near.org/tools/fastauth-sdk but have encountered an issue with the CLI. When attempting to use the 'near generate-key' command, I received a message indicating that the command is deprecated in the new NEAR CLI, and I couldn't locate an alternative solution.

Additionally, when trying to use the 'add-key' command, I received an error message stating that the 'add-key' command or the near-add-key extension does not exist. Any assistance or guidance on these issues would be greatly appreciated. 

Thank you for your help.

**Comment by FroVolod** [comment]
You may have an old version of "NEAR CLI". Check its relevance: https://github.com/near/near-cli-rs/releases/tag/v0.7.4  

![example1](https://github.com/near/near-cli-rs/assets/36816899/6966d3f6-83ce-4fd0-ad86-424efa61647e)
