### ISSUE TITLE
Error on smart-contract update using base64

### ISSUE THREAD

**Issue by VlodkoMr** [near/near-cli-rs#296]
I get error when try to upload new version of the smart-contract using near-cli-rs:
`argument list too long: near`

Call to update smart-contract:
```
CONTRACT_BYTES=`cat ./res/contract.wasm | base64`

near-cli-rs contract call-function as-transaction "$CONTRACT" unsafe_self_upgrade base64-args "$CONTRACT_BYTES" prepaid-gas '300 TeraGas' attached-deposit '0 NEAR' sign-as $OWNER_ACCOUNT network-config testnet sign-with-keychain send
```

Smart-contract wasm file size: 212Kb
OS: Ubuntu 20.04 on **Windows WSL 2.0**
NOTE: The same error with near-cli.

**Comment by frol** [comment]
@VlodkoMr Please, share you smart contract code `unsafe_self_upgrade` function implementation and the transaction on chain (I believe this error comes from the contract side, actually)

**Comment by VlodkoMr** [comment]
Issue based on usage Ubuntu 20.04 on Windows WSL 2.0, tested on MacOS and all work fine

**Comment by frol** [comment]
Ah, I see, well, use `file-args` (instead of `base64-args`) and just specify the path to the Wasm file instead of reading and passing it as base64-encoded string. That is your shell that complains about the size of the shell command
