### ISSUE TITLE
Implement keychain support in WSL (Linux on Windows)

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#299]
It seems that near.cli.rs cannot use system keychain to store and read keys on WSL (Linux subsystem on Windows): https://github.com/near/near-cli-rs/issues/287#issuecomment-1935586950

It needs further investigation if there is a way to get system keychain working in WSL and if there is a need to change anything in near.cli.rs for that.

Meanwhile, if you use WSL, use legacy keychain to manage the keys.

**Comment by AlexKushnir1** [comment]
I can work on this!
