### ISSUE TITLE
Option to run non-interactive cli

### ISSUE THREAD

**Issue by elliotBraem** [near/near-cli-rs#305]
One of the best things about this tool is it's interactivity -- however, without the option to disable it, this interactivity can cause issue in non-interactive containers.

For example, attempting to use `near config add-connection --network-name mainnet --connection-name mainnet --rpc-url https://rpc.mainnet.near.org/ --wallet-url https://app.mynearwallet.com/ --explorer-transaction-url https://nearblocks.io/txns/` (which holds all of the information I want to provide) asks me several questions that cause `The input device is not a TTY` errors in my container (git workflow).

If you see the screenshot below, I don't think any of these questions needed my explicit answers and could have been assumed/ignored.

<img width="781" alt="Screenshot 2024-02-21 at 12 15 51 PM" src="https://github.com/near/near-cli-rs/assets/16282460/c5b0d9c0-c6c6-40ca-b053-20f23f260e2c">

I think this could be solved with a --non-interactive flag

**Comment by frol** [comment]
Yeah, `config` subcommand needs some love. Just to mention a workaround here, you can just write the config file directly to the `config.toml` file under the [config directory](https://github.com/near/near-cli-rs/blob/main/docs/README.en.md#config)
