### ISSUE TITLE
Transaction expires / times out due to archival-rpc in config

### ISSUE THREAD

**Issue by petersalomonsen** [near/near-cli-rs#306]
A newly installed near-cli is configured to use archival-rpc:

<img width="771" alt="image" src="https://github.com/near/near-cli-rs/assets/9760441/453a68ac-70a8-437e-ae5a-b1b86c59395f">

This cause many transaction to expire/time out (like this build https://github.com/NEAR-DevHub/neardevhub-bos/actions/runs/8009365088/job/21879301976#step:6:311 ). Changing to the standard rpc fixes the issue.

It seems like the archival RPC is set up as a default here:

https://github.com/near/near-cli-rs/blob/37f0449531351e55236fbb913622f97cef28bfb4/src/config.rs#L21

**Comment by frol** [comment]
Archival RPC default is by design. We don't want users to get confusing errors when they are trying to get the status of a transaction or some other view calls that need the data older than 2 days.
