### ISSUE TITLE
Add posibility to output to file instead of console for large transactions

### ISSUE THREAD

**Issue by dj8yfo** [near/near-cli-rs#308]
https://github.com/near/near-cli-rs/blob/main/src/transaction_signature_options/sign_later/mod.rs#L38

**Comment by frol** [comment]
In addition to `send` and `display` commands, we may introduce `save-to-file "path"` command. In the particular case of `sign-later` we don't even have `send` / `display` switch yet, so we would need to introduce `display` / `save-to-file` subcommands, similarly to `Submit`:

https://github.com/near/near-cli-rs/blob/62d6f3aa7f7c600aa3e83d763aee465f17c93e48/src/transaction_signature_options/sign_with_access_key_file/mod.rs#L25-L26

And we will also need to extend the `Submit` enum with the `SaveToFile` variant:

https://github.com/near/near-cli-rs/blob/62d6f3aa7f7c600aa3e83d763aee465f17c93e48/src/transaction_signature_options/mod.rs#L65-L74
