### ISSUE TITLE
Display the transaction fee in NEAR and approximate $ after transaction is executed

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#320]
So after any transaction being executed, we currently display logs, status, and link to Explorer, and I suggest we add a summary of the transaction fees in NEAR and USD equivalent.

<img width="931" alt="image" src="https://github.com/near/near-cli-rs/assets/304265/17ff32f9-91a7-44eb-8208-3837ea049d9f">

Here is the function you need to apply the changes: https://github.com/near/near-cli-rs/blob/a1bde9a58dbba0fdaa7813d02752488cd9ec761e/src/common.rs#L1102-L1107

**Comment by amiremohamadi** [comment]
I'll be taking on this issue and working on a solution. just to make sure, by fee you mean the gas amount in `ExecutionOutcomeView::gas_burnt`?
