### ISSUE TITLE
Runtime Introspection

### ISSUE THREAD

**Issue by miraclx** [near/near-cli-rs#321]
What do you think about setting up a log subscriber for the binary, `near-jsonrpc-client`, for example uses `log` internally, and I would like to be able to see those reports when running the CLI.

**Comment by frol** [comment]
@miraclx do you mean you want to be able to control logging level via env variable RUST_LOG?

You can do that starting with a recent 0.10.0 release:

https://github.com/near/near-cli-rs/blob/21001b6d6c6c6fb05ba1f5d267029de4af680beb/src/main.rs#L91
