### ISSUE TITLE
Signing a transaction with Ledger fails if the transaction is "too" big

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#33]
Certain transactions like those that involve contract deployment or huge blob of arguments in a function call read to an obscure error, which was already reported here [https://github.com/near/near-cli/issues/612](https://github.com/near/near-cli/issues/612) and here https://github.com/LedgerHQ/app-near/issues/13

**There is no solution yet. Further discussion should happen in the thread mentioned above.**

**Comment by frol** [comment]
It is an implementation of on-Ledger app (https://github.com/near/app-near), which is limited by the memory constraint of Ledger device ([4KiB of RAM](https://developers.ledger.com/docs/nano-app/troubleshooting/#not-enough-ram)). NEAR app on Ledger allocates [650 bytes for the transaction buffer](https://github.com/near/app-near/blob/master/workdir/app-near/src/constants.h#L4), and so it is a hard limit at the moment unless someone implements some streaming mechanism: https://github.com/near/near-cli/issues/612#issuecomment-927695848

**Comment by 0x3bfc** [comment]
Same issue here while using the `deploy action` for deploying contract where it is signed by ledger.

```bash
near contract deploy <MYACCOUNT_ID> use-file /tmp/contract.wasm without-init-call network-config testnet sign-with-ledger --seed-phrase-hd-path 'm/44'\''/397'\''/0'\''/0'\''/1'\'''
Error: 
   0: Error occurred while signing the transaction: APDUExchangeError("Unknown Ledger APDU retcode: 27024")

Location:
   /Users/ahmed/.cargo/registry/src/github.com-1ecc6299db9ec823/near-cli-rs-0.5.1/src/transaction_signature_options/sign_with_ledger/mod.rs:97
```

The main issue is mainly related to the near-app for ledger.
