### ISSUE TITLE
Duplicated Tracing Message

### ISSUE THREAD

**Issue by frolvanya** [near/near-cli-rs#335]
Tracing messages are duplicated when a function with a `tracing::instrument` attribute macro 
(`#[tracing::instrument(skip_all, name = "...")]`) calls another function that also generates output. This duplication occurs due to how tracing manages loader-refreshing. It necessitates erasing the previously printed line and printing the new log line with a new loader state. However, the issue arises because new output moves the cursor with freshly generated output, causing the duplication of tracing messages.

To mitigate this problem, I propose rewriting the code so that `eprintln`-s are positioned outside of the method that is instrumented.

Current workaround with tracing message suspension during the function call: https://github.com/near/near-cli-rs/blob/21001b6d6c6c6fb05ba1f5d267029de4af680beb/src/transaction_signature_options/send/mod.rs#L64-L72

Example of "Sending transaction ..." message duplication:
![image](https://github.com/near/near-cli-rs/assets/59515280/de9578ae-02f3-49c0-b25d-db456f9b0484)

Expected behavior:
![image](https://github.com/near/near-cli-rs/assets/59515280/69119c76-a383-4201-9818-db17b5848b85)

**Comment by frol** [comment]
Resolved with #339
