### ISSUE TITLE
Required allowance for Function-Call Keys

### ISSUE THREAD

**Issue by pustovalov** [near/near-cli-rs#341]
Hi,

After this PR:

https://github.com/near/near-cli-rs/pull/330

`allowance` attribute became required, but the documentation states that this attribute is optional:

https://docs.near.org/concepts/protocol/access-keys#function-call-keys

```
allowance (Optional): The amount of NEAR allowed to be spent on gas. If omitted, the key can consume unlimited as gas
```

Which implementation is correct?

**Comment by frol** [comment]
@pustovalov good catch. We had an internal discussion and thought that nobody would actually need that unlimited allowance any time soon. @FroVolod will jump on it now to introduce proper parsing of “--allowance unlimited”, cause absent CLI option is ambiguous
