### ISSUE TITLE
Testnet faucet potentially not working

### ISSUE THREAD

**Issue by globart** [near/near-cli-rs#348]
I've encountered this error today:
`Error: 0: error sending request for url (https://helper.nearprotocol.com/account): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known` 
when issuing this command ("account_name" and "seedphrase" are placeholders, their values are valid):
`near account create-account sponsor-by-faucet-service account_name.testnet use-manually-provided-seed-phrase 'seedphrase' network-config testnet create`

**Comment by frol** [comment]
The faucet service is currently not reachable. We reported it to the maintainer. In the meanwhile, use https://near-faucet.io

**Comment by frol** [comment]
The faucet service is back online and operates as expected, so I close this issue since there are no action items
