### ISSUE TITLE
[Enhancement] Add an option to edit configs

### ISSUE THREAD

**Issue by gagdiez** [near/near-cli-rs#365]
We are currently at a hackathon, and the official RPC went down. It would be nice to be able to quickly edit the fields on the existing config, so users can change RPC in seconds.

**Comment by frol** [comment]
@gagdiez How do you feel about adding more default configurations out of the box to have multiple RPCs to select from? so instead of just `mainnet` there could be `mainnet-pagoda-rpc`, `mainnet-fastnear-rpc`, ...

**Comment by gagdiez** [comment]
Sounds like an amazing idea to me
