### ISSUE TITLE
Update explorer to nearblocks

### ISSUE THREAD

**Issue by PiVortex** [near/near-cli-rs#368]
By default transactions links are given for the old explorer, [for example](https://explorer.testnet.near.org/transactions/BHg5yq9zdN9GjBfTityx1zpFoE24mzCGSTECxGDkbgiC)

This should be updated to, by default, transaction links being given for nearblocks [for example](https://testnet.nearblocks.io/txns/BHg5yq9zdN9GjBfTityx1zpFoE24mzCGSTECxGDkbgiC)

**Comment by frol** [comment]
Pagoda should deploy Explorer Selector to explorer.testnet.near.org and then we won't need to change it here

**Comment by frol** [comment]
https://explorer.testnet.near.org now hosts Explorer Selector, so this issue can be closed.
