### ISSUE TITLE
[BUG] view-near-balance command fails

### ISSUE THREAD

**Issue by garikbesson** [near/near-cli-rs#384]
Details are on the screenshot. 

Testnet RPC is default:
rpc_url = "https://archival-rpc.testnet.near.org/"

The command doesn't work for me on the mainnet either (default RPC).

<img width="681" alt="image" src="https://github.com/user-attachments/assets/e5a1ad35-4996-4149-926e-1f46442fcc57">

**Comment by frol** [comment]
It will be resolved with #381
