### ISSUE TITLE
[BUG] deposit-and-stake action retrieves validator list only for mainnet

### ISSUE THREAD

**Issue by garikbesson** [near/near-cli-rs#387]
Before selecting the network `deposit-and-stake` action retrieves the validator list only for the mainnet. This makes it impossible to stake assets on testnet.

Pic. 1
![image](https://github.com/user-attachments/assets/3c2216f7-128c-4e43-9caa-ccad24551ec8)

Pic. 2
<img width="689" alt="image" src="https://github.com/user-attachments/assets/8d5c9aae-6511-4a30-abd1-45673951fd64">

**Comment by frol** [comment]
@garikbesson I'd say it is pointless to delegate stake on testnet, so it was a conscious decision to skip testnet. Do you have a specific use-case where stake delegation is used on testnet?

**Comment by frol** [comment]
I will close this issue as there is no action item at the moment, but feel free to reopen it with more details provided.

**Comment by garikbesson** [comment]
> Do you have a specific use case where stake delegation is used on testnet?

I think it can be such use cases as development/debugging new liquid staking tools or people who go through the validator node setup guide and want to try testnet firstly

But those are certainly rare cases
