### ISSUE TITLE
Recreate account issues with keys

### ISSUE THREAD

**Issue by PiVortex** [near/near-cli-rs#395]
**Problem**
A common use of the CLI could be to delete an account and create an account with the same accountId. If the file that stores your keys is not deleted then the new full access key will not be added to the file and you won't be able to access the account once created again.

**To reproduce**
- I create an account and store my keys in legacy keychain
- I delete the account 
- I create an account with the same name as before and store my keys in legacy keychain
- I try to perform a transaction using my account but I don't have the keys to do so 

It may not be suitable to just delete the file with the old keys if one were to delete the account another way.

**Comment by FroVolod** [comment]
> If the file that stores your keys is not deleted then the new full access key will not be added to the file and you won't be able to access the account once created again.


This is not so.
The key file will not be overwritten, but the key will be added to a directory called "your_account_id".
Right now you can find that key in that directory and sign the transaction.
I will solve this problem soon.
Thank you for your inquiry.
