### ISSUE TITLE
Don't work create account

### ISSUE THREAD

**Issue by tverdoy** [near/near-cli-rs#400]
### What talent are you looking for?

None

### What you need to be done?

create account

### Currency

USDC.e

### KYC

- [ ] Use KYC Verification

**Comment by tverdoy** [comment]
I try create account:

**Comment by zhil** [comment]
@tverdoy with latest version of CLI you should be able to use short syntax with default configuration, it works just fine

```
near create-account your-name-here.testnet --useFaucet
```

my config
```
explorer_transaction_url: "https://explorer.testnet.near.org/transactions/"
  fastnear_url: null
  faucet_url: "https://helper.nearprotocol.com/account"
  linkdrop_account_id: "testnet"
  meta_transaction_relayer_url: null
v near_social_db_contract_account_id: "v1.social08.testnet"
```
