### ISSUE TITLE
Serialization issues with calling testnet smart contract due to incompatibility with v1.82

### ISSUE THREAD

**Issue by s-n-park** [near/near-cli-rs#411]
Context:
- Recently walking through the simple testnet smart contract deployment example on [Docs](https://docs.near.org/build/smart-contracts/quickstart)

The Issue:
- After successful deployment of smart contract of [sp-testing-proximity.testnet](https://testnet.nearblocks.io/address/sp-testing-proximity.testnet), when trying to make a function call, I ran into the following error:

> Error: 
> 0: Error: An error occurred during a FunctionCall Action, parameter is debug message.
>       CompilationError(PrepareError(Deserialization))
> 

The solution:
- On [Discord](https://discord.com/channels/490367152054992913/1265474510178750494/1299161587529158657) @PiVortex had noted this can been resolved by:
- Downgrading to 1.81.0 (navigated to smart contract directory and ran rustup override set 1.81.0, and then redeploying the smart contract. See my notes on resolution in [Discord](https://discord.com/channels/490367152054992913/1265474510178750494/1303426922058874890)

Request:
-  Wanted to see if it's possible to fix this issue via the NEAR CLI to be compatible with 1.82? Feel free to migrate issue if this is not the correct repo to note on.

CC: @frol , @gagdiez, @PiVortex

**Comment by PiVortex** [comment]
This can be resolved by upgrading to the most recent version of cargo-near and using the most recent version of near workspaces. This is not do with the CLI AFIAK

**Comment by s-n-park** [comment]
Thanks for your help!
