### ISSUE TITLE
[BUG] Transaction link uses deprecated `explorer.near.org` address

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-cli-rs#418]
### Background

Transaction links provided in the console summary use the deprecated `explorer.near.org` address and should use `nearblocks.io` or similar. 

`Example:`

```bash
Gas burned: 17.0 Tgas
Transaction fee: 0.001608566867888 NEAR
Transaction ID: 3TBv37NiKQuao9Rou5dHxh3kezEpfrMLCNN48zhNRqrx
To see the transaction in the transaction explorer, please open this url in your browser:
https://explorer.testnet.near.org/transactions/3TBv37NiKQuao9Rou5dHxh3kezEpfrMLCNN48zhNRqrx
```

### User Story

As a developer I would expect to be directed to a working site :) 

### Acceptance Criteria

- [ ] update both `mainnet` and `testnet` explorer links to use nearblocks.io or similar

### Priority

🟡 P2 : Medium

**Comment by frol** [comment]
explorer.near.org is not deprecated, it is a selector of all available Explorers.

Closing it as duplicated of #368
