### ISSUE TITLE
Write working interface to deploy contract.

### ISSUE THREAD

**Issue by volovyks** [near/near-cli-rs#43]
Write working interface to deploy contract.
 Currently seems like the logic is in here:
 [https://github.com/FroVolod/near-cli/blob/12dfa268b72ba4778aedf898361f46c5136fc75f/src/commands/add_command/contract_code/contract/mod.rs#L165-L195](https://github.com/FroVolod/near-cli/blob/12dfa268b72ba4778aedf898361f46c5136fc75f/src/commands/add_command/contract_code/contract/mod.rs#L165-L195)
 User should be able to use "near deploy" if I'm understanding the CLI proposal where it says "other aliases of contract-transaction"
 [https://gov.near.org/t/new-near-cli-design-proposal/3616#commands-18](https://gov.near.org/t/new-near-cli-design-proposal/3616#commands-18)

**Comment by frol** [comment]
@volovyk-s before we jump into changing the individual commands layout, I suggest we sit down and write [full commands we currently have](https://github.com/near/near-cli-rs/blob/master/docs/GUIDE.en.md) into the new proposed style on a single page to see how they fit together. Extracting `deploy` to the top level command seems to be quite a stretch. Even in the proposed design, it is not `near deploy`, but `near dev deploy`.

**Comment by volovyk-s** [comment]
@frol ok, I was not planning to do that right now.
Here is a separate issue for that: https://github.com/near/near-cli-rs/issues/46

**Comment by frol** [comment]
New commands layout was implemented, so I'm closing this as completed
