### ISSUE TITLE
`view-account-summary` method doesn't work on `testnet` network

### ISSUE THREAD

**Issue by frolvanya** [near/near-cli-rs#431]
<img width="963" alt="image" src="https://github.com/user-attachments/assets/69b8bf87-2680-401b-bd8e-f99f297c0fdd" />

`view-account-summary` is crashing constantly during getting the staked balance. I'm not sure why it happens since `testnet` only has 28 nodes of validators compared to 500+ on `mainnet`, but I assume it can be fixed by splitting all validators by smaller chunks and process them one by one with a small delay in-between. If this won't help, let's at least display all other information that we can like social, native account balance, storage used and number of access keys

**Comment by akorchyn** [comment]
@frolvanya, invite you to review #433 :)
