### ISSUE TITLE
Write working interface for function call

### ISSUE THREAD

**Issue by volovyks** [near/near-cli-rs#45]
Currently: [https://github.com/FroVolod/near-cli/blob/master/docs/GUIDE.en.md#execute-function-contract-method](https://github.com/FroVolod/near-cli/blob/master/docs/GUIDE.en.md#execute-function-contract-method)
 Should be: "near call" if I'm reading correctly from the "other aliases" part of: [https://gov.near.org/t/new-near-cli-design-proposal/3616#commands-18](https://gov.near.org/t/new-near-cli-design-proposal/3616#commands-18)

**Comment by jberrytech** [comment]
Sprint planning notes: blocked by interactive CLI.

**Comment by frol** [comment]
New commands layout was implemented, so I'm closing this as completed
