### ISSUE TITLE
Avoid getting balances to suggest max values in prompt

### ISSUE THREAD

**Issue by khorolets** [near/near-cli-rs#53]
I was playing around the localnet and was creating an account with initial balances. Interactive prompts were suggesting values. It is localnet, so I've accepted them.

Command looked like

```
./near-cli add sub-account network custom --url http://localhost:3030/ owner-account test.near sub-account check.test.near sub-account-full-access generate-keypair deposit '999999989.9985186679375 NEAR' sign-with-keychain send
```

The result of this was

```
Transaction sent ...
Your console command:
...
```

The transaction wasn't actually sent and no error appeared. 

Decreasing the value for `deposit` made everything work as expected. The cause of the problem that suggested deposit value was an entire balance of my account. Sending transaction with this amount of tokens is impossible because nothing is even left for covering the transaction fees.

**I suggest** we stop suggesting any values for a deposit or transfer values as it might be dangerous. Let's just throw an error about "not enough funds" or something similar and let users decide what they want to do instead.

**Comment by frol** [comment]
It was resolved during the migration to interactive-clap, which is included in 0.1.15 release.
