### ISSUE TITLE
Improve You console command by giving the right binary name

### ISSUE THREAD

**Issue by khorolets** [near/near-cli-rs#54]
First of all @FroVolod thanks for the feature #36 It's amazing! 

I suggest a small improvement to the feature. It always returns my console command as if I was calling `./near-cli` binary. However, I have the binary system-wide and this `./near-cli` makes my experience a bit worse. 

As far as I know, it's possible to replace that value with the 0s element from the input. 

It's not much but a great improvement. Thanks!

**Comment by frol** [comment]
This was addressed in #87
