### ISSUE TITLE
Environment variables support

### ISSUE THREAD

**Issue by khorolets** [near/near-cli-rs#57]
I think users can benefit from env support. I propose we collect a list of useful parameters that can benefit from envs.

*   `network`
     I'm testing stuff on localnet and it can be annoying to select "Custom" network all the time and provide RPC endpoint URL `[http://localhost:3030](http://localhost:3030)` every time. We could solve this by editing predefined LocalNet to the list, but assuming users might want to use their own URL it's not a great solution.

Please feel free to add other parameters you may find useful in terms of envs support

**Comment by frol** [comment]
*This comment is motivated by #101*

Someone should invest their time into designing a solution to set default presets through a config file. E.g. extending a list of predefined networks with a way to configure access keys for RPC-as-a-Service (DevConsole) RPC servers, etc.

**Comment by frol** [comment]
Configuration file was introduced in 0.2 version of CLI, so now you can add arbitrary number of network configurations.

@frovolod please, add "configuration" section to the README files to highlight this feature

**Comment by frol** [comment]
Closing in favor of #123
