### ISSUE TITLE
[BUG] "cli help" does not work correctly

### ISSUE THREAD

**Issue by FroVolod** [near/near-cli-rs#65]
![Screenshot 2021-09-23 at 13 07 13](https://user-images.githubusercontent.com/36816899/134494882-c074739b-dd94-4651-a2c5-bb83b1317870.png)

**Comment by FroVolod** [comment]
It happened in release 0.1.14

**Comment by frol** [comment]
Resolved in https://github.com/near/near-cli-rs/commit/3a867a8d8e95ed309d226f3620c4440c9049ad3b
