### ISSUE TITLE
Show contract method names

### ISSUE THREAD

**Issue by frol** [near/near-cli-rs#70]
I have just seen an issue reported on near-cli JS ([https://github.com/near/near-cli/issues/849](https://github.com/near/near-cli/issues/849)), which I believe we should be able to implement as an extension, but let's keep a tracking record here.

**Comment by frol** [comment]
Previously, I thought about having a separate CLI extension for development, but recently, I changed my mind, and I actually believe that CLI is already a devtool, so we should have the developer tools in the near.cli.rs.

That said, I believe it is worth adding the method to inspect contract interface, especially when ABI is available (https://github.com/near/near-cli-rs/pull/92#issuecomment-1287698460):

```
near contract inspect "contract_account_id" network-config mainnet now
```

The expected output should at least provide the list of available function names, but if ABI is available, it should print the functions as TypeScript and/or Rust function signatures, see `cargo near abi` for reference.

**Comment by vsmysle** [comment]
Working on this issue.
