### ISSUE TITLE
non-english input is not displayed properly

### ISSUE THREAD

**Issue by adsick** [near/near-cli-rs#97]
If you try inputting some non-latin text (e.g. cyrillic) you will see that the view is wrong. This is due to the fact that we use `dialoguer::prompts::input::Input::interact_text()` method and as it's doc-comment says: it "Enables the user to enter a printable ascii sequence and returns the result." (ascii is the key word here)

This is not much of a problem as most users only type latin, but if someone wants to enter some args in e.g. Russian that will cause a bit of pain for the user.

<span class="error">[example of interact_text() method in our codebase]</span>([https://github.com/near/near-cli-rs/blob/525703fcdaca6080d3898a35c25bafd8fc2ffc25/src/commands/execute_command/change_method/call_function_type/mod.rs#L54](https://github.com/near/near-cli-rs/blob/525703fcdaca6080d3898a35c25bafd8fc2ffc25/src/commands/execute_command/change_method/call_function_type/mod.rs#L54))

**Comment by frol** [comment]
Thanks for reporting it. I wonder if dialoguer will consider fixing it

**Comment by frol** [comment]
I think `dialoguer` (the crate that is used for the inputs here) is not going to fix it, so I believe we should switch to [`inquire`](https://github.com/mikaelmello/inquire) in [`interactive-clap`](https://github.com/FroVolod/interactive-clap). Contributions are welcome!
