### ISSUE TITLE
Add keys to keychain access for OS X users

### ISSUE THREAD

**Issue by mikedotexe** [near/near-cli-rs#98]
Instead of storing the private keys in unencrypted files, we can consider using something like Keychain Access in OS X. (There are other options with Linux and Windows, but this ticket is just for OS X)

It looks like there's a crate that helps connect to Apple's "Core Foundation" which allows various integrations.

Here's some general docs from Apple about this:
 [https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain](https://developer.apple.com/documentation/security/keychain_services/keychain_items/adding_a_password_to_the_keychain)

Here's a crate to tap into Core Foundation:
 [https://lib.rs/crates/core-foundation](https://lib.rs/crates/core-foundation)

Here's a Golang implementation for storing keys that could be helpful:
 [https://github.com/99designs/go-keychain/blob/master/keychain.go](https://github.com/99designs/go-keychain/blob/master/keychain.go)

**Comment by frol** [comment]
MacOS Keychain support is now implemented! See #122
